# TESTING COFUSION MATRIX TANPA PACKAGE

In [1]:
import numpy as np

cm = np.array([[5825,    1,   49,   23,    7,   46,   30,   12,   21,   26],
               [1, 6654,   48,   25,   10,   32,   19,   62,  111,   10],
               [2,   20, 5561,   69,   13,   10,    2,   45,   18,    2],
               [6,   26,   99, 5786,    5,  111,    1,   41,  110,   79],
               [4,   10,   43,    6, 5533,   32,   11,   53,   34,   79],
               [3,    1,    2,   56,    0, 4954,   23,    0,   12,    5],
               [31,    4,   42,   22,   45,  103, 5806,    3,   34,    3],
               [0,    4,   30,   29,    5,    6,    0, 5817,    2,   28],
               [35,    6,   63,   58,    8,   59,   26,   13, 5394,   24],
               [16,   16,   21,   57,  216,   68,    0,  219,  115, 5693]])

In [2]:
print(cm)

[[5825    1   49   23    7   46   30   12   21   26]
 [   1 6654   48   25   10   32   19   62  111   10]
 [   2   20 5561   69   13   10    2   45   18    2]
 [   6   26   99 5786    5  111    1   41  110   79]
 [   4   10   43    6 5533   32   11   53   34   79]
 [   3    1    2   56    0 4954   23    0   12    5]
 [  31    4   42   22   45  103 5806    3   34    3]
 [   0    4   30   29    5    6    0 5817    2   28]
 [  35    6   63   58    8   59   26   13 5394   24]
 [  16   16   21   57  216   68    0  219  115 5693]]


In [3]:
def precision(label, confusion_matrix):
    col = confusion_matrix[:, label]
    return confusion_matrix[label, label]/col.sum()

def recall(label, confusion_matrix):
    row = confusion_matrix[label,:]
    return confusion_matrix[label, label]/row.sum()

def precision_macro_avrage(confusion_matrix):
    rows, columns = confusion_matrix.shape
    sum_of_precisions = 0
    for label in range(rows):
        sum_of_precisions += precision(label, confusion_matrix)
    return sum_of_precisions/rows

def recall_macro_avrage(confusion_matrix):
    rows, columns = confusion_matrix.shape
    sum_of_recall = 0
    for label in range(columns):
        sum_of_recall += recall(label, confusion_matrix)
    return sum_of_recall/columns

# HASIL PENGUJIAN PRECISION dan RECALL

In [4]:
print("label precision recall")
for label in range(10):
    print(f"{label:5d} {precision(label, cm):9.3f} {recall(label, cm):6.3f}")

label precision recall
    0     0.983  0.964
    1     0.987  0.954
    2     0.933  0.968
    3     0.944  0.924
    4     0.947  0.953
    5     0.914  0.980
    6     0.981  0.953
    7     0.928  0.982
    8     0.922  0.949
    9     0.957  0.887


In [5]:
print("total precison", precision_macro_avrage(cm))

total precison 0.9496885564052286


In [6]:
print("total recall", recall_macro_avrage(cm))

total recall 0.9514531547877969


In [7]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_element = confusion_matrix.sum()
    return diagonal_sum/sum_of_all_element

In [8]:
print(accuracy(cm))

0.9503833333333334


In [9]:
print("Nilai Pembulatan ", round(accuracy(cm),2))

Nilai Pembulatan  0.95


# TESTING COFUSION MATRIX Menggunakan packge sckit Learning

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
#from sklearn.metrics import plot_confusion_matrix

In [11]:
data = pd.read_csv('data.csv')

In [12]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [13]:
print(data.shape)

(569, 33)


In [14]:
X = pd.DataFrame(data.iloc[:,2:6])
y = pd.DataFrame(data.iloc[:,1:2])

In [15]:
print("5 paling atas data fitur: \n" , X.head())
print("=========================")
print("5 paling atas data kelas: \n" , y.head())

5 paling atas data fitur: 
    radius_mean  texture_mean  perimeter_mean  area_mean
0        17.99         10.38          122.80     1001.0
1        20.57         17.77          132.90     1326.0
2        19.69         21.25          130.00     1203.0
3        11.42         20.38           77.58      386.1
4        20.29         14.34          135.10     1297.0
5 paling atas data kelas: 
   diagnosis
0         M
1         M
2         M
3         M
4         M


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

In [17]:
from sklearn import svm
model_SVM = svm.SVC(kernel='linear')
model_SVM.fit(X_train, y_train)
y_predict = model_SVM.predict(X_test)

/home/cak/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# TESTING

In [18]:
prediksi = model_SVM.predict([[17.99, 10.38, 122.80, 1001.0]])
if prediksi == "M":
    print(prediksi, "Pasien terkena kangker dengan kondisi GANAS.!")
else:
    print(prediksi, "Pasien terkena kangker dengan kondisi JINAK")

['M'] Pasien terkena kangker dengan kondisi GANAS.!


In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_predict)
print(confusion_matrix)

[[66  6]
 [ 8 34]]


In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           B       0.89      0.92      0.90        72
           M       0.85      0.81      0.83        42

    accuracy                           0.88       114
   macro avg       0.87      0.86      0.87       114
weighted avg       0.88      0.88      0.88       114

